### ISSUE TITLE
FailedInternalRequestException has invalid argument type

### ISSUE THREAD

**Issue by igrslv** [matthewbdaly/laravel-internal-requests#1]
Hello,

in latest Laravel versions if request contains  'HTTP_Accept' => 'application/json' header the handle result will be an object of \Illuminate\Http\JsonResponse class. The current implementation throws an exception in a case of a bad request:

`testing.ERROR: Argument 2 passed to Matthewbdaly\LaravelInternalRequests\Exceptions\FailedInternalRequestException::__construct() must be an instance of Illuminate\Http\Response, instance of Illuminate\Http\JsonResponse given, called in /home/ihar/Project/vendor/matthewbdaly/laravel-internal-requests/src/Services/InternalRequest.php on line 49`

Thanks

**Comment by matthewbdaly** [comment]
Figured it out - the `JsonResponse` is no longer based on the Laravel `Response` object, so typehinting it didn't work. Instead, it's now based on the Symfony counterpart, so amending it to typehint Symfony responses instead solved the issue.

I've made a new release that includes the fix. Any chance you can install it and check it works for you?

**Comment by igrslv** [comment]
Yes, it's working now. Thanks!

**Comment by matthewbdaly** [comment]
Cool. I will close this issue then.
